package com.futsch1.medtimer

import android.graphics.Color
import com.futsch1.medtimer.database.FullMedicineEntity
import com.futsch1.medtimer.database.JSONMedicineBackup
import com.futsch1.medtimer.database.MedicineEntity
import com.futsch1.medtimer.database.ReminderEntity
import com.futsch1.medtimer.database.TagEntity
import org.junit.Test
import org.mockito.kotlin.mock
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertNull


internal class JSONMedicineBackupUnitTest {
    // Generated by CodiumAI
    // creates a backup object with a version number and a medicines array
    @Test
    fun testCreatesBackupWithVersionAndMedicinesArray() {
        val jsonMedicineBackup = JSONMedicineBackup(mock(), mock(), mock())

        val medicinesWithReminders = listOf(FullMedicineEntity().apply {
            reminders = mutableListOf(ReminderEntity(0).apply {
                reminderId = 14
                timeInMinutes = 60
                amount = "1"
                consecutiveDays = 1
                pauseDays = 0
                cycleStartDay = 12
                instructions = "Take with water"
                periodStart = 13
                days[0] = false
                activeDaysOfMonth = 7
                linkedReminderId = 15
                automaticallyTaken = true
                intervalStartTimeOfDay = 1
                intervalEndTimeOfDay = 2
                outOfStockThreshold = 1.0
                outOfStockReminderType = ReminderEntity.OutOfStockReminderType.ONCE
                expirationReminderType = ReminderEntity.ExpirationReminderType.DAILY
            })
            medicine = MedicineEntity("Medicine A").apply {
                useColor = true
                color = Color.RED
                iconId = 5
                unit = "pills"
                sortOrder = 4.5
                notes = "Generic ingredient: Dihydrogen monoxide"
                showNotificationAsAlarm = true
                productionDate = 1
                expirationDate = 2
            }
            tags = listOf(TagEntity("Tag A"))
        })

        val result = assertNotNull(jsonMedicineBackup.createBackupAsString(5, medicinesWithReminders))

        // @formatter:off
        assertEquals("""
{
  "version": 5,
  "list": [
    {
      "medicine": {
        "name": "Medicine A",
        "color": -65536,
        "useColor": true,
        "notificationImportance": 3,
        "iconId": 5,
        "amount": 0.0,
        "refillSizes": [],
        "unit": "pills",
        "sortOrder": 4.5,
        "notes": "Generic ingredient: Dihydrogen monoxide",
        "showNotificationAsAlarm": true,
        "productionDate": 1,
        "expirationDate": 2
      },
      "tags": [
        {
          "name": "Tag A"
        }
      ],
      "reminders": [
        {
          "reminderId": 14,
          "timeInMinutes": 60,
          "consecutiveDays": 1,
          "pauseDays": 0,
          "instructions": "Take with water",
          "cycleStartDay": 12,
          "amount": "1",
          "days": [
            false,
            true,
            true,
            true,
            true,
            true,
            true
          ],
          "active": true,
          "periodStart": 13,
          "periodEnd": 0,
          "activeDaysOfMonth": 7,
          "linkedReminderId": 15,
          "intervalStart": 0,
          "intervalStartsFromProcessed": false,
          "variableAmount": false,
          "automaticallyTaken": true,
          "intervalStartTimeOfDay": 1,
          "intervalEndTimeOfDay": 2,
          "windowedInterval": false,
          "outOfStockThreshold": 1.0,
          "outOfStockReminderType": "ONCE",
          "expirationReminderType": "DAILY"
        }
      ]
    }
  ]
}
""".trimIndent(), result)
        
                // @formatter:on
        val parsedReminders = assertNotNull(jsonMedicineBackup.parseBackup(result))
        compareListFullMedicine(parsedReminders, medicinesWithReminders)
    }

    private fun compareListFullMedicine(
        actual: List<FullMedicineEntity>,
        expected: List<FullMedicineEntity>
    ) {
        assertEquals(expected.size, actual.size)
        for (i in actual.indices) {
            compareFullMedicine(actual.get(i), expected.get(i))
        }
    }

    private fun compareFullMedicine(
        medicineWithReminders: FullMedicineEntity,
        medicineWithReminders1: FullMedicineEntity
    ) {
        assertEquals(
            medicineWithReminders.reminders.size,
            medicineWithReminders1.reminders.size
        )
        for (i in medicineWithReminders.reminders.indices) {
            compareReminder(
                medicineWithReminders.reminders.get(i),
                medicineWithReminders1.reminders.get(i)
            )
        }
        assertEquals(
            medicineWithReminders.medicine.name,
            medicineWithReminders1.medicine.name
        )
        assertEquals(
            medicineWithReminders.medicine.useColor,
            medicineWithReminders1.medicine.useColor
        )
        assertEquals(
            medicineWithReminders.medicine.color,
            medicineWithReminders1.medicine.color
        )
    }

    private fun compareReminder(reminder: ReminderEntity, reminder1: ReminderEntity) {
        assertEquals(reminder.timeInMinutes, reminder1.timeInMinutes)
        assertEquals(reminder.consecutiveDays, reminder1.consecutiveDays)
        assertEquals(reminder.instructions, reminder1.instructions)
        assertEquals(reminder.amount, reminder1.amount)
    }

    // iterates over the list of FullMedicine and adds each one to the medicines array as a JSONObject
    @Test
    fun testIteratesOverMedicinesWithRemindersAndAddsToMedicinesArray() {
        val reminder1 = ReminderEntity(0).apply {
            reminderId = 1
            timeInMinutes = 60
            amount = "1"
            consecutiveDays = 1
            pauseDays = 0
            cycleStartDay = 1234
            instructions = "Take with water"
            activeDaysOfMonth = -1
        }

        val reminder2 = ReminderEntity(0).apply {
            reminderId = 2
            timeInMinutes = 120
            amount = "2"
            consecutiveDays = 2
            pauseDays = 1
            cycleStartDay = 4567
            instructions = "Take after meal"
            days[6] = false
            activeDaysOfMonth = 255
            linkedReminderId = 234
            intervalStart = 256
            intervalStartsFromProcessed = true
            variableAmount = true
        }

        val medicinesWithReminders = mutableListOf(
            FullMedicineEntity().apply {
                reminders = mutableListOf(reminder1)
                medicine = MedicineEntity("Medicine A")
                medicine.useColor = true
                medicine.color = Color.RED
                medicine.notificationImportance = 4
                medicine.sortOrder = 3.44
            }, FullMedicineEntity().apply {
                reminders = mutableListOf(reminder1, reminder2)
                medicine = MedicineEntity("Medicine B")
                medicine.useColor = false
                medicine.color = Color.BLUE
                medicine.notificationImportance = 5
                medicine.iconId = 7
                medicine.amount = 17.0
            }
        )

        val jsonMedicineBackup = JSONMedicineBackup(mock(), mock(), mock())
        val result = assertNotNull(jsonMedicineBackup.createBackupAsString(4, medicinesWithReminders))

        // @formatter:off
        assertEquals("""
{
  "version": 4,
  "list": [
    {
      "medicine": {
        "name": "Medicine A",
        "color": -65536,
        "useColor": true,
        "notificationImportance": 4,
        "iconId": 0,
        "amount": 0.0,
        "refillSizes": [],
        "unit": "",
        "sortOrder": 3.44,
        "notes": "",
        "showNotificationAsAlarm": false,
        "productionDate": 0,
        "expirationDate": 0
      },
      "tags": [],
      "reminders": [
        {
          "reminderId": 1,
          "timeInMinutes": 60,
          "consecutiveDays": 1,
          "pauseDays": 0,
          "instructions": "Take with water",
          "cycleStartDay": 1234,
          "amount": "1",
          "days": [
            true,
            true,
            true,
            true,
            true,
            true,
            true
          ],
          "active": true,
          "periodStart": 0,
          "periodEnd": 0,
          "activeDaysOfMonth": -1,
          "linkedReminderId": 0,
          "intervalStart": 0,
          "intervalStartsFromProcessed": false,
          "variableAmount": false,
          "automaticallyTaken": false,
          "intervalStartTimeOfDay": 480,
          "intervalEndTimeOfDay": 1320,
          "windowedInterval": false,
          "outOfStockThreshold": 0.0,
          "outOfStockReminderType": "OFF",
          "expirationReminderType": "OFF"
        }
      ]
    },
    {
      "medicine": {
        "name": "Medicine B",
        "color": -16776961,
        "useColor": false,
        "notificationImportance": 5,
        "iconId": 7,
        "amount": 17.0,
        "refillSizes": [],
        "unit": "",
        "sortOrder": 1.0,
        "notes": "",
        "showNotificationAsAlarm": false,
        "productionDate": 0,
        "expirationDate": 0
      },
      "tags": [],
      "reminders": [
        {
          "reminderId": 1,
          "timeInMinutes": 60,
          "consecutiveDays": 1,
          "pauseDays": 0,
          "instructions": "Take with water",
          "cycleStartDay": 1234,
          "amount": "1",
          "days": [
            true,
            true,
            true,
            true,
            true,
            true,
            true
          ],
          "active": true,
          "periodStart": 0,
          "periodEnd": 0,
          "activeDaysOfMonth": -1,
          "linkedReminderId": 0,
          "intervalStart": 0,
          "intervalStartsFromProcessed": false,
          "variableAmount": false,
          "automaticallyTaken": false,
          "intervalStartTimeOfDay": 480,
          "intervalEndTimeOfDay": 1320,
          "windowedInterval": false,
          "outOfStockThreshold": 0.0,
          "outOfStockReminderType": "OFF",
          "expirationReminderType": "OFF"
        },
        {
          "reminderId": 2,
          "timeInMinutes": 120,
          "consecutiveDays": 2,
          "pauseDays": 1,
          "instructions": "Take after meal",
          "cycleStartDay": 4567,
          "amount": "2",
          "days": [
            true,
            true,
            true,
            true,
            true,
            true,
            false
          ],
          "active": true,
          "periodStart": 0,
          "periodEnd": 0,
          "activeDaysOfMonth": 255,
          "linkedReminderId": 234,
          "intervalStart": 256,
          "intervalStartsFromProcessed": true,
          "variableAmount": true,
          "automaticallyTaken": false,
          "intervalStartTimeOfDay": 480,
          "intervalEndTimeOfDay": 1320,
          "windowedInterval": false,
          "outOfStockThreshold": 0.0,
          "outOfStockReminderType": "OFF",
          "expirationReminderType": "OFF"
        }
      ]
    }
  ]
}
""".trimIndent(), result)
        
                // @formatter:on
        val parsedReminders = assertNotNull(jsonMedicineBackup.parseBackup(result))
        compareListFullMedicine(parsedReminders, medicinesWithReminders)
    }

    @Test
    fun testParseJsonBackupMissingFields() {
        // Arrange
        val jsonMedicineBackup = JSONMedicineBackup(mock(), mock(), mock())
        val validJsonBackup =
            "{\"version\": 1, \"medicinesWithReminders\": [{\"reminders\": [], \"medicine\": {}}]}"

        // Act
        val result = jsonMedicineBackup.parseBackup(validJsonBackup)

        // Assert
        assertNull(result)
    }

    @Test
    fun testParseInvalidJsonBackup() {
        // Arrange
        val jsonMedicineBackup = JSONMedicineBackup(mock(), mock(), mock())
        val invalidJsonBackup = "invalid_json"

        // Act
        val result = jsonMedicineBackup.parseBackup(invalidJsonBackup)

        // Assert
        assertNull(result)
    }

    @Test
    fun testParseJsonBackupWithMissingFields() {
        // Arrange
        val jsonMedicineBackup = JSONMedicineBackup(mock(), mock(), mock())
        val jsonBackupWithMissingFields = "{\"version\": 1}"

        // Act
        val result =
            jsonMedicineBackup.parseBackup(jsonBackupWithMissingFields)

        // Assert
        assertNull(result)
    }
}

