package com.futsch1.medtimer;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

import android.graphics.Color;

import com.futsch1.medtimer.database.JSONBackup;
import com.futsch1.medtimer.database.Medicine;
import com.futsch1.medtimer.database.MedicineWithReminders;
import com.futsch1.medtimer.database.Reminder;

import org.json.JSONException;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.robolectric.RobolectricTestRunner;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

@RunWith(RobolectricTestRunner.class)
public class JSONBackupUnitTest {

    // Generated by CodiumAI

    // creates a backup object with a version number and a medicines array
    @Test
    public void test_creates_backup_with_version_and_medicines_array() {
        JSONBackup jsonBackup = new JSONBackup();
        List<MedicineWithReminders> medicinesWithReminders = new ArrayList<>();
        MedicineWithReminders medicineWithReminders = new MedicineWithReminders();
        Reminder reminder = new Reminder(0);
        reminder.timeInMinutes = 60;
        reminder.amount = "1";
        reminder.daysBetweenReminders = 1;
        reminder.instructions = "Take with water";
        medicineWithReminders.reminders = Collections.singletonList(reminder);
        medicineWithReminders.medicine = new Medicine("Medicine A");
        medicineWithReminders.medicine.useColor = true;
        medicineWithReminders.medicine.color = Color.RED;
        medicinesWithReminders.add(medicineWithReminders);

        String result = jsonBackup.createBackup(5, medicinesWithReminders);

        assertNotNull(result);

        // @formatter:off
        assertEquals("""
{
  "version": 5,
  "medicinesWithReminders": [
    {
      "reminders": [
        {
          "timeInMinutes": 60,
          "createdTimestamp": 0,
          "daysBetweenReminders": 1,
          "instructions": "Take with water",
          "amount": "1"
        }
      ],
      "medicine": {
        "name": "Medicine A",
        "color": -65536,
        "useColor": true
      }
    }
  ]
}""", result);
        // @formatter:on
    }

    // iterates over the list of MedicineWithReminders and adds each one to the medicines array as a JSONObject
    @Test
    public void test_iterates_over_medicinesWithReminders_and_adds_to_medicines_array() throws JSONException {
        JSONBackup jsonBackup = new JSONBackup();
        List<MedicineWithReminders> medicinesWithReminders = new ArrayList<>();
        MedicineWithReminders medicineWithReminders1 = new MedicineWithReminders();
        Reminder reminder1 = new Reminder(0);
        reminder1.timeInMinutes = 60;
        reminder1.amount = "1";
        reminder1.daysBetweenReminders = 1;
        reminder1.instructions = "Take with water";
        medicineWithReminders1.reminders = Collections.singletonList(reminder1);
        medicineWithReminders1.medicine = new Medicine("Medicine A");
        medicineWithReminders1.medicine.useColor = true;
        medicineWithReminders1.medicine.color = Color.RED;
        medicinesWithReminders.add(medicineWithReminders1);

        MedicineWithReminders medicineWithReminders2 = new MedicineWithReminders();
        Reminder reminder2 = new Reminder(0);
        reminder2.timeInMinutes = 120;
        reminder2.amount = "2";
        reminder2.daysBetweenReminders = 2;
        reminder2.instructions = "Take after meal";
        medicineWithReminders2.reminders = new ArrayList<>() {{
            add(reminder1);
            add(reminder2);
        }};
        medicineWithReminders2.medicine = new Medicine("Medicine B");
        medicineWithReminders2.medicine.useColor = false;
        medicineWithReminders2.medicine.color = Color.BLUE;
        medicinesWithReminders.add(medicineWithReminders2);

        String result = jsonBackup.createBackup(4, medicinesWithReminders);

        assertNotNull(result);

        // @formatter:off
        assertEquals("""
{
  "version": 4,
  "medicinesWithReminders": [
    {
      "reminders": [
        {
          "timeInMinutes": 60,
          "createdTimestamp": 0,
          "daysBetweenReminders": 1,
          "instructions": "Take with water",
          "amount": "1"
        }
      ],
      "medicine": {
        "name": "Medicine A",
        "color": -65536,
        "useColor": true
      }
    },
    {
      "reminders": [
        {
          "timeInMinutes": 60,
          "createdTimestamp": 0,
          "daysBetweenReminders": 1,
          "instructions": "Take with water",
          "amount": "1"
        },
        {
          "timeInMinutes": 120,
          "createdTimestamp": 0,
          "daysBetweenReminders": 2,
          "instructions": "Take after meal",
          "amount": "2"
        }
      ],
      "medicine": {
        "name": "Medicine B",
        "color": -16776961,
        "useColor": false
      }
    }
  ]
}""", result);
        // @formatter:on

    }

}

