package com.futsch1.medtimer;


import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;

import android.graphics.Color;

import com.futsch1.medtimer.database.FullMedicine;
import com.futsch1.medtimer.database.JSONMedicineBackup;
import com.futsch1.medtimer.database.Medicine;
import com.futsch1.medtimer.database.Reminder;
import com.futsch1.medtimer.database.Tag;

import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

class JSONMedicineBackupUnitTest {

    // Generated by CodiumAI

    // creates a backup object with a version number and a medicines array
    @Test
    void testCreatesBackupWithVersionAndMedicinesArray() {
        JSONMedicineBackup jsonMedicineBackup = new JSONMedicineBackup();
        List<FullMedicine> medicinesWithReminders = new ArrayList<>();
        FullMedicine medicineWithReminders = new FullMedicine();
        Reminder reminder = new Reminder(0);
        reminder.setReminderId(14);
        reminder.setTimeInMinutes(60);
        reminder.setAmount("1");
        reminder.setConsecutiveDays(1);
        reminder.setPauseDays(0);
        reminder.setCycleStartDay(12);
        reminder.setInstructions("Take with water");
        reminder.setPeriodStart(13);
        reminder.getDays().set(0, false);
        reminder.setActiveDaysOfMonth(7);
        reminder.setLinkedReminderId(15);
        reminder.setAutomaticallyTaken(true);
        reminder.setIntervalStartTimeOfDay(1);
        reminder.setIntervalEndTimeOfDay(2);
        reminder.setOutOfStockThreshold(1.0);
        reminder.setOutOfStockReminderType(Reminder.OutOfStockReminderType.ONCE);
        reminder.setExpirationReminderType(Reminder.ExpirationReminderType.DAILY);
        medicineWithReminders.setReminders(Collections.singletonList(reminder));
        medicineWithReminders.setMedicine(new Medicine("Medicine A"));
        medicineWithReminders.getMedicine().setUseColor(true);
        medicineWithReminders.getMedicine().setColor(Color.RED);
        medicineWithReminders.getMedicine().setIconId(5);
        medicineWithReminders.getMedicine().setUnit("pills");
        medicineWithReminders.getMedicine().setSortOrder(4.5);
        medicineWithReminders.getMedicine().setNotes("Generic ingredient: Dihydrogen monoxide");
        medicineWithReminders.getMedicine().setShowNotificationAsAlarm(true);
        medicineWithReminders.getMedicine().setProductionDate(1);
        medicineWithReminders.getMedicine().setExpirationDate(2);
        medicineWithReminders.setTags(new ArrayList<>());
        medicineWithReminders.getTags().add(new Tag("Tag A"));
        medicinesWithReminders.add(medicineWithReminders);

        String result = jsonMedicineBackup.createBackupAsString(5, medicinesWithReminders);

        assertNotNull(result);

        // @formatter:off
        assertEquals("""
{
  "version": 5,
  "list": [
    {
      "medicine": {
        "name": "Medicine A",
        "color": -65536,
        "useColor": true,
        "notificationImportance": 3,
        "iconId": 5,
        "amount": 0.0,
        "refillSizes": [],
        "unit": "pills",
        "sortOrder": 4.5,
        "notes": "Generic ingredient: Dihydrogen monoxide",
        "showNotificationAsAlarm": true,
        "productionDate": 1,
        "expirationDate": 2
      },
      "tags": [
        {
          "name": "Tag A"
        }
      ],
      "reminders": [
        {
          "reminderId": 14,
          "timeInMinutes": 60,
          "consecutiveDays": 1,
          "pauseDays": 0,
          "instructions": "Take with water",
          "cycleStartDay": 12,
          "amount": "1",
          "days": [
            false,
            true,
            true,
            true,
            true,
            true,
            true
          ],
          "active": true,
          "periodStart": 13,
          "periodEnd": 0,
          "activeDaysOfMonth": 7,
          "linkedReminderId": 15,
          "intervalStart": 0,
          "intervalStartsFromProcessed": false,
          "variableAmount": false,
          "automaticallyTaken": true,
          "intervalStartTimeOfDay": 1,
          "intervalEndTimeOfDay": 2,
          "windowedInterval": false,
          "outOfStockThreshold": 1.0,
          "outOfStockReminderType": "ONCE",
          "expirationReminderType": "DAILY"
        }
      ]
    }
  ]
}""", result);
        // @formatter:on

        List<FullMedicine> parsedReminders = jsonMedicineBackup.parseBackup(result);
        assertNotNull(parsedReminders);
        compareListFullMedicine(parsedReminders, medicinesWithReminders);
    }

    private void compareListFullMedicine(List<FullMedicine> actual, List<FullMedicine> expected) {
        assertEquals(expected.size(), actual.size());
        for (int i = 0; i < actual.size(); i++) {
            compareFullMedicine(actual.get(i), expected.get(i));
        }
    }

    private void compareFullMedicine(FullMedicine medicineWithReminders, FullMedicine medicineWithReminders1) {
        assertEquals(medicineWithReminders.getReminders().size(), medicineWithReminders1.getReminders().size());
        for (int i = 0; i < medicineWithReminders.getReminders().size(); i++) {
            compareReminder(medicineWithReminders.getReminders().get(i), medicineWithReminders1.getReminders().get(i));
        }
        assertEquals(medicineWithReminders.getMedicine().getName(), medicineWithReminders1.getMedicine().getName());
        assertEquals(medicineWithReminders.getMedicine().getUseColor(), medicineWithReminders1.getMedicine().getUseColor());
        assertEquals(medicineWithReminders.getMedicine().getColor(), medicineWithReminders1.getMedicine().getColor());
    }

    private void compareReminder(Reminder reminder, Reminder reminder1) {
        assertEquals(reminder.getTimeInMinutes(), reminder1.getTimeInMinutes());
        assertEquals(reminder.getConsecutiveDays(), reminder1.getConsecutiveDays());
        assertEquals(reminder.getInstructions(), reminder1.getInstructions());
        assertEquals(reminder.getAmount(), reminder1.getAmount());
    }

    // iterates over the list of FullMedicine and adds each one to the medicines array as a JSONObject
    @Test
    void testIteratesOverMedicinesWithRemindersAndAddsToMedicinesArray() {
        JSONMedicineBackup jsonMedicineBackup = new JSONMedicineBackup();
        List<FullMedicine> medicinesWithReminders = new ArrayList<>();
        FullMedicine medicineWithReminders1 = new FullMedicine();
        Reminder reminder1 = new Reminder(0);
        reminder1.setReminderId(1);
        reminder1.setTimeInMinutes(60);
        reminder1.setAmount("1");
        reminder1.setConsecutiveDays(1);
        reminder1.setPauseDays(0);
        reminder1.setCycleStartDay(1234);
        reminder1.setInstructions("Take with water");
        reminder1.setActiveDaysOfMonth(0xFFFF_FFFF);
        medicineWithReminders1.setReminders(Collections.singletonList(reminder1));
        medicineWithReminders1.setMedicine(new Medicine("Medicine A"));
        medicineWithReminders1.getMedicine().setUseColor(true);
        medicineWithReminders1.getMedicine().setColor(Color.RED);
        medicineWithReminders1.getMedicine().setNotificationImportance(4);
        medicineWithReminders1.getMedicine().setSortOrder(3.44);
        medicinesWithReminders.add(medicineWithReminders1);

        FullMedicine medicineWithReminders2 = new FullMedicine();
        Reminder reminder2 = new Reminder(0);
        reminder2.setReminderId(2);
        reminder2.setTimeInMinutes(120);
        reminder2.setAmount("2");
        reminder2.setConsecutiveDays(2);
        reminder2.setPauseDays(1);
        reminder2.setCycleStartDay(4567);
        reminder2.setInstructions("Take after meal");
        reminder2.getDays().set(6, false);
        reminder2.setActiveDaysOfMonth(255);
        reminder2.setLinkedReminderId(234);
        reminder2.setIntervalStart(256);
        reminder2.setIntervalStartsFromProcessed(true);
        reminder2.setVariableAmount(true);
        medicineWithReminders2.setReminders(new ArrayList<>() {{
            add(reminder1);
            add(reminder2);
        }});
        medicineWithReminders2.setMedicine(new Medicine("Medicine B"));
        medicineWithReminders2.getMedicine().setUseColor(false);
        medicineWithReminders2.getMedicine().setColor(Color.BLUE);
        medicineWithReminders2.getMedicine().setNotificationImportance(5);
        medicineWithReminders2.getMedicine().setIconId(7);
        medicineWithReminders2.getMedicine().setAmount(17.0);
        medicinesWithReminders.add(medicineWithReminders2);

        String result = jsonMedicineBackup.createBackupAsString(4, medicinesWithReminders);

        assertNotNull(result);

        // @formatter:off
        assertEquals("""
{
  "version": 4,
  "list": [
    {
      "medicine": {
        "name": "Medicine A",
        "color": -65536,
        "useColor": true,
        "notificationImportance": 4,
        "iconId": 0,
        "amount": 0.0,
        "refillSizes": [],
        "unit": "",
        "sortOrder": 3.44,
        "notes": "",
        "showNotificationAsAlarm": false,
        "productionDate": 0,
        "expirationDate": 0
      },
      "tags": [],
      "reminders": [
        {
          "reminderId": 1,
          "timeInMinutes": 60,
          "consecutiveDays": 1,
          "pauseDays": 0,
          "instructions": "Take with water",
          "cycleStartDay": 1234,
          "amount": "1",
          "days": [
            true,
            true,
            true,
            true,
            true,
            true,
            true
          ],
          "active": true,
          "periodStart": 0,
          "periodEnd": 0,
          "activeDaysOfMonth": -1,
          "linkedReminderId": 0,
          "intervalStart": 0,
          "intervalStartsFromProcessed": false,
          "variableAmount": false,
          "automaticallyTaken": false,
          "intervalStartTimeOfDay": 480,
          "intervalEndTimeOfDay": 1320,
          "windowedInterval": false,
          "outOfStockThreshold": 0.0,
          "outOfStockReminderType": "OFF",
          "expirationReminderType": "OFF"
        }
      ]
    },
    {
      "medicine": {
        "name": "Medicine B",
        "color": -16776961,
        "useColor": false,
        "notificationImportance": 5,
        "iconId": 7,
        "amount": 17.0,
        "refillSizes": [],
        "unit": "",
        "sortOrder": 1.0,
        "notes": "",
        "showNotificationAsAlarm": false,
        "productionDate": 0,
        "expirationDate": 0
      },
      "tags": [],
      "reminders": [
        {
          "reminderId": 1,
          "timeInMinutes": 60,
          "consecutiveDays": 1,
          "pauseDays": 0,
          "instructions": "Take with water",
          "cycleStartDay": 1234,
          "amount": "1",
          "days": [
            true,
            true,
            true,
            true,
            true,
            true,
            true
          ],
          "active": true,
          "periodStart": 0,
          "periodEnd": 0,
          "activeDaysOfMonth": -1,
          "linkedReminderId": 0,
          "intervalStart": 0,
          "intervalStartsFromProcessed": false,
          "variableAmount": false,
          "automaticallyTaken": false,
          "intervalStartTimeOfDay": 480,
          "intervalEndTimeOfDay": 1320,
          "windowedInterval": false,
          "outOfStockThreshold": 0.0,
          "outOfStockReminderType": "OFF",
          "expirationReminderType": "OFF"
        },
        {
          "reminderId": 2,
          "timeInMinutes": 120,
          "consecutiveDays": 2,
          "pauseDays": 1,
          "instructions": "Take after meal",
          "cycleStartDay": 4567,
          "amount": "2",
          "days": [
            true,
            true,
            true,
            true,
            true,
            true,
            false
          ],
          "active": true,
          "periodStart": 0,
          "periodEnd": 0,
          "activeDaysOfMonth": 255,
          "linkedReminderId": 234,
          "intervalStart": 256,
          "intervalStartsFromProcessed": true,
          "variableAmount": true,
          "automaticallyTaken": false,
          "intervalStartTimeOfDay": 480,
          "intervalEndTimeOfDay": 1320,
          "windowedInterval": false,
          "outOfStockThreshold": 0.0,
          "outOfStockReminderType": "OFF",
          "expirationReminderType": "OFF"
        }
      ]
    }
  ]
}""", result);
        // @formatter:on

        List<FullMedicine> parsedReminders = jsonMedicineBackup.parseBackup(result);
        assertNotNull(parsedReminders);
        compareListFullMedicine(parsedReminders, medicinesWithReminders);
    }

    @Test
    void testParseJsonBackupMissingFields() {
        // Arrange
        JSONMedicineBackup jsonMedicineBackup = new JSONMedicineBackup();
        String validJsonBackup = "{\"version\": 1, \"medicinesWithReminders\": [{\"reminders\": [], \"medicine\": {}}]}";

        // Act
        List<FullMedicine> result = jsonMedicineBackup.parseBackup(validJsonBackup);

        // Assert
        assertNull(result);
    }

    @Test
    void testParseInvalidJsonBackup() {
        // Arrange
        JSONMedicineBackup jsonMedicineBackup = new JSONMedicineBackup();
        String invalidJsonBackup = "invalid_json";

        // Act
        List<FullMedicine> result = jsonMedicineBackup.parseBackup(invalidJsonBackup);

        // Assert
        assertNull(result);
    }

    @Test
    void testParseJsonBackupWithMissingFields() {
        // Arrange
        JSONMedicineBackup jsonMedicineBackup = new JSONMedicineBackup();
        String jsonBackupWithMissingFields = "{\"version\": 1}";

        // Act
        List<FullMedicine> result = jsonMedicineBackup.parseBackup(jsonBackupWithMissingFields);

        // Assert
        assertNull(result);
    }

}

