# Customize this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version("2.221.1")

default_platform(:android)

platform(:android) do
  desc("Build debug and test APK for screenshots")
  lane(:build_and_screengrab) do
    gradle(task: "assembleDebug assembleAndroidTest")
    capture_android_screenshots
  end

end